name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build CAS
      run: |
        sudo apt-get update -y
        sudo apt-get install -y lzma libbz2-dev libcurl4-openssl-dev
        git submodule init
        git submodule update --init --recursive
        make -C htslib
        mkdir build
        make print
    - name: Run test
      run: |
        tar -xvzf test/DUP180.tar.gz
        cas --bam 180.sub.bam --range chr1:6400-6900
        if [ "$(tail -n 1 predictedEvents.bed | cut -f 1)" = "chr1" ]; then return 0; else return 1; fi
        if [ "$(tail -n 1 predictedEvents.bed | cut -f 2)" = "6567" ]; then return 0; else return 1; fi
        if [ "$(tail -n 1 predictedEvents.bed | cut -f 3)" = "6751" ]; then return 0; else return 1; fi
